### PR TITLE
Create filter box for author affiliations #14

### PR DESCRIPTION
**Pull request by huylesitdn**

### CODE REVIEW

**Comment by colinrsmall** [comment]
Looks really good! Thanks Huy!

Before I merge, can you add a quick fix to the PR limiting the height of fully expanded filter boxes? Instead of fully expanding, it would be nice if they were limited in height allowing a user to scroll through the list of filter values. For example, if you open a model with a lot of papers (like novel object recognition) on the app and click show all for a filter box, it will expand the full height of the filter box far too much to be user friendly.

**Comment by huylesitdn** [comment]
@colinrsmall I updated

**Comment by colinrsmall** [comment]
Thanks. A few more small tweaks:

image

1. Can you add a bit of padding around each list item to visually separate them? 
2. It looks like the checkboxes do not properly line up with each line item. (May be solved by adding padding in tweak 1).
3. Can you increase the max height of the affiliation filter box to allow the "Specific Affiliation" sub-box to properly expand when a user clicks show all? Right now, clicking that button doesn't actually change the height of the box.
4. Can you add some indicator to the filter boxes to help users know that they can scroll through the list? Perhaps have the scroll bar always appear in the list?

**Comment by huylesitdn** [comment]
@colinrsmall i just updated. 

i have add max-height for "Specific Affiliation" container items is 500px and show scrollbar on it

image

**Comment by huylesitdn** [comment]
@colinrsmall i using chrome on macos

**Pull request merged**
