### PR TITLE
Condition filters bug out when affiliation filters change #33

### PR DESCRIPTION
**Pull request by huylesitdn**

### CODE REVIEW

**Comment by colinrsmall** [comment]
Sorry, I should have specified earlier but condition filters should remain selected if a user selects an affiliation filter. We shouldn't just be resetting the selected affiliation filters.

**Comment by colinrsmall** [comment]
I'm sorry, I'm not sure I understand your question. If a user has not selected any filters (condition or affiliation), all paper results and filter options should be displayed to the user. A user could then do one of two things:

1. They select an affiliation filter. The paper results should be filtered (like they are now) and the condition filter options should be updated to display only the relevant options from the filtered papers. The affiliation filter options shouldn't change. If there is no previously checked condition filter when a user selects an affiliation filter, then the paper results only get filtered by affiliation. Because there will be fewer paper results after filtering, there should be fewer condition options for the user to filter from afterwards. If a user had previously selected a condition filter (see below), the only affiliation filter options they should be able to select from should be those from the now-condition-filtered  set of paper results.
2. They select a condition filter. The paper results should be filtered (like they are now) and the affiliation filter options should be updated to display only the affiliations of authors from the filtered paper results.

The user should never be able to select filters such that no papers will be displayed. 

Does that answer things?

**Comment by huylesitdn** [comment]
@colinrsmall In short, what you mean is that selected "condition filter" filters need to be displayed even if they are not in "affiliation filter" list (not reset all "condition filters" when selecting "affiliation filter" like I just updated), right?

**Comment by colinrsmall** [comment]
Yes

**Comment by huylesitdn** [comment]
@colinrsmall please re-check, 
please pull backend with same name as thisbranch
https://github.com/ModernVivo/mv_backend/pull/20

**Comment by colinrsmall** [comment]
Looks good in testing, thanks!

**Pull request merged**
